### PR TITLE
Move the limited parts of verify_mfaable into authy_authenticatable

### PR DESCRIPTION
**Pull request by wwahammy**
As described in #85, verify_mfaable doesn't make sense outside of its use by authy_authenticatable. So this combines the two.

### CODE REVIEW

**Comment by camckin10** [comment]
@wwahammy Can you please update the PR description to explain why this change is necessary?

**Comment by wwahammy** [comment]
> @wwahammy Can you please update the PR description to explain why this change is necessary?

I figured the link to the issue was sufficient. But I'll add it.

**Comment by wwahammy** [comment]
> @wwahammy Can you please update the PR description to explain why this change is necessary?

done.

**Review by camckin10 — APPROVED** [review]
👍

**Comment by BintLopez** [comment]
Question on the issue -- does it make more sense to consolidate under non authy naming since authy is what's being phased out? https://github.com/MidwestAccessCoalition/twilio-verify-devise/issues/85#issuecomment-2218389911

**Review by BintLopez — APPROVED** [review]
🦑

**Pull request merged**
